setwd("C:/docs (3rd year)/chem160module11")
redcell<-read.table("redcell.txt", header=T)
names(redcell)
is.factor(redcell$ventilation)
plot(folate~ventilation, data=redcell)
model<-lm(folate~ventilation, data=redcell)
summary(model)
